services:
  # Django application service
  django-archaeology:
    build: .
    volumes:
      - .:/home/archaeology
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: postgres
      POSTGRES_DB: postgres2
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: dev-insecure-secret-key
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # Database service
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres2
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    depends_on:
      - db
